### PR TITLE
Fixed #41 (Mark.pipes.sanitize) by adding or's to the regex; added tests

### LINKED ISSUE #41: | sanitize not working?
I just tried to get the sanitize filter to work, but it's not working as expected.
1. I'm including `markup.js`
2. I'm including `extras/strings.js`
3. I'm using the `| sanitize` pipe in my placeholder

Please check the codepen. In the JS tab I first included markup.js, then extras/strings.js and finally used sanitize (at the end of the tab, sorry for the unconvenient handling, did not find markup.js on cdnjs):

http://codepen.io/anon/pen/yNyQLN

The link in the output should not be a link after `| sanitize`.

Best
Marc

### PR DESCRIPTION
**Pull request by mdix**
Fixed and tested, please merge. If you have a better solution for the input <-> output mapping than the empty elements I used please let me know.

### CODE REVIEW

**Comment by adammark** [comment]
Thanks—I'll review this ASAP.

**Comment by twilight-app** [comment]
:thumbsup:

**Comment by mdix** [comment]
I needed another feature, so I added it: A filter that replaces a given string with another string. I called it str_replace. Maybe you can also merge this if you like to.

**Comment by mdix** [comment]
I needed another feature, so I added it: A filter that replaces a given string with another string. I called it str_replace. Maybe you can also merge this if you like to.

**Comment by mdix** [comment]
So?

**Comment by adammark** [comment]
This looks good. I don't think we need to bump the version number, as you've only made changes in /extras. Can you revert package.json and markup.min.js, then I'll merge? Thanks!

**Pull request closed without merging**
